#!/bin/sh
export SEMEVAL_HOME=/local_home/lipn/SemEval/
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.input.MSRpar.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.gs.MSRpar.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2012.test.input.MSRpar.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2012.test.input.MSRpar.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.input.MSRvid.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.gs.MSRvid.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2012.test.input.MSRvid.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2012.test.input.MSRvid.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.input.SMTeuroparl.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.gs.SMTeuroparl.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2012.test.input.SMTeuroparl.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2012.test.input.SMTeuroparl.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.input.surprise.OnWN.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.gs.surprise.OnWN.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2012.test.input.surprise.OnWN.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2012.test.input.surprise.OnWN.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.input.surprise.SMTnews.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.test.gs.surprise.SMTnews.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2012.test.input.surprise.SMTnews.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2012.test.input.surprise.SMTnews.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.train.input.MSRpar.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.train.gs.MSRpar.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2012.train.input.MSRpar.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2012.train.input.MSRpar.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.train.input.MSRvid.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.train.gs.MSRvid.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2012.train.input.MSRvid.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2012.train.input.MSRvid.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.train.input.SMTeuroparl.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2012.train.gs.SMTeuroparl.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2012.train.input.SMTeuroparl.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2012.train.input.SMTeuroparl.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2013.test.input.FNWN.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2013.test.gs.FNWN.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2013.test.input.FNWN.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2013.test.input.FNWN.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2013.test.input.headlines.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2013.test.gs.headlines.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2013.test.input.headlines.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2013.test.input.headlines.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2013.test.input.OnWN.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2013.test.gs.OnWN.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2013.test.input.OnWN.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2013.test.input.OnWN.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2013.test.input.SMT.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2013.test.gs.SMT.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2013.test.input.SMT.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2013.test.input.SMT.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.input.local2.sentences.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.gs.local2.sentences.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2014.input.local2.sentences.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2014.input.local2.sentences.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.input.local.pairs-journals.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.gs.local.pairs-journals.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2014.input.local.pairs-journals.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2014.input.local.pairs-journals.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.input.local.sentences.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.gs.local.sentences.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2014.input.local.sentences.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2014.input.local.sentences.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.test.input.news.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.test.gs.news.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2014.test.input.news.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2014.test.input.news.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.test.input.wikipedia.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.test.gs.wikipedia.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2014.test.input.wikipedia.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2014.test.input.wikipedia.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.train.input.li65.txt $SEMEVAL_HOME/spanish_testbed/data/train/STS.2014.train.gs.li65.txt > $SEMEVAL_HOME/spanish_testbed/analysis/results/STS.2014.train.input.li65.dat 2>$SEMEVAL_HOME/spanish_testbed/analysis/logs/STS.2014.train.input.li65.log
