SEMEVAL_HOME=/home/jgflores/experimentos/SemEval/sopa.2015/SemEval/dat
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.input.MSRpar.txt $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.gs.MSRpar.txt > $SEMEVAL_HOME/testbed/analysis/2015/training/results/STS.2012.test.input.MSRpar.dat 2>$SEMEVAL_HOME/testbed/analysis/2015/training/logs/STS.2012.test.input.MSRpar.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.input.MSRvid.txt $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.gs.MSRvid.txt > $SEMEVAL_HOME/testbed/analysis/2015/training/results/STS.2012.test.input.MSRvid.dat 2>$SEMEVAL_HOME/testbed/analysis/2015/training/logs/STS.2012.test.input.MSRvid.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.input.SMTeuroparl.txt $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.gs.SMTeuroparl.txt > $SEMEVAL_HOME/testbed/analysis/2015/training/results/STS.2012.test.input.SMTeuroparl.dat 2>$SEMEVAL_HOME/testbed/analysis/2015/training/logs/STS.2012.test.input.SMTeuroparl.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.input.surprise.OnWN.txt $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.gs.surprise.OnWN.txt > $SEMEVAL_HOME/testbed/analysis/2015/training/results/STS.2012.test.input.surprise.OnWN.dat 2>$SEMEVAL_HOME/testbed/analysis/2015/training/logs/STS.2012.test.input.surprise.OnWN.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.input.surprise.SMTnews.txt $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.test.gs.surprise.SMTnews.txt > $SEMEVAL_HOME/testbed/analysis/2015/training/results/STS.2012.test.input.surprise.SMTnews.dat 2>$SEMEVAL_HOME/testbed/analysis/2015/training/logs/STS.2012.test.input.surprise.SMTnews.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.train.input.MSRpar.txt $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.train.gs.MSRpar.txt > $SEMEVAL_HOME/testbed/analysis/2015/training/results/STS.2012.train.input.MSRpar.dat 2>$SEMEVAL_HOME/testbed/analysis/2015/training/logs/STS.2012.train.input.MSRpar.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.train.input.MSRvid.txt $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.train.gs.MSRvid.txt > $SEMEVAL_HOME/testbed/analysis/2015/training/results/STS.2012.train.input.MSRvid.dat 2>$SEMEVAL_HOME/testbed/analysis/2015/training/logs/STS.2012.train.input.MSRvid.log
./run.semantic.comparer.with.train.sh $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.train.input.SMTeuroparl.txt $SEMEVAL_HOME/testbed//data/2014/train/STS.2012.train.gs.SMTeuroparl.txt > $SEMEVAL_HOME/testbed/analysis/2015/training/results/STS.2012.train.input.SMTeuroparl.dat 2>$SEMEVAL_HOME/testbed/analysis/2015/training/logs/STS.2012.train.input.SMTeuroparl.log
